---
app_name: "<your app name>"

# Your Telegram phone number | With quotes
telegram_phone: "<your phone number>"

# Your Telegram password (Two-step verification) | With quotes
telegram_password: "<your password>"

# This has to be an integer. Read more [here](https://core.telegram.org/api/obtaining_api_id) | No quotes
telegram_api_id: <your api id>

# Long 32 characters hash identifier. Read more [here](https://core.telegram.org/api/obtaining_api_id) | With quotes
telegram_api_hash: "<your api hash>"

# Discord Bot Token. Go create a bot on discord. | No quotes
discord_bot_token: <your discord bot token>

# The channels map to discord channels.
telegram_forwarders:
  - forwarder_name: "<forwarder_name>"
    tg_channel_id: <tg channel id>
    discord_channel_id: <discord channel id>
    mention_everyone: True
    forward_everything: False # whether forwarding everything regardless the hashtag
    hashtags:
      - name: "#example1"
        override_mention_everyone: True
      - name: "#example6"

  - forwarder_name: "<forwarder_name>"
    tg_channel_id: <tg channel id>
    discord_channel_id: <discord channel id>
    mention_everyone: False
    forward_everything: False # whether forwarding everything regardless the hashtag
    hashtags:
      - name: "#example3"
        override_mention_everyone: True
      - name: "#example4"
